apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-backend
  namespace: expensetracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-backend
  template:
    metadata:
      labels:
        app: expense-backend
    spec:
      containers:
        - name: expense-backend
          image: vasanth32674/expense-backend:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: expense-backend
  namespace: expensetracker
spec:
  selector:
    app: expense-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
