apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-frontend
  namespace: expensetracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-frontend
  template:
    metadata:
      labels:
        app: expense-frontend
    spec:
      containers:
        - name: expense-frontend
          image: vasanth32674/expense-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: expense-frontend
  namespace: expensetracker
spec:
  selector:
    app: expense-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
