name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # BACKEND BUILD (Maven)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend with Maven
        working-directory: ./moneymanager
        run: mvn -B clean package -DskipTests

      # LOGIN DOCKER HUB
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # FRONTEND BUILD & PUSH
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./moneymanagerwebapp
          file: ./moneymanagerwebapp/Dockerfile
          push: true
          tags: |
            vasanth32674/expense-frontend:latest

      # BACKEND BUILD & PUSH
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./moneymanager
          file: ./moneymanager/Dockerfile
          push: true
          tags: |
            vasanth32674/expense-backend:latest
